apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: WildFly S2I builder, JDK 17
  name: wildfly-s2i-jdk17
spec:
  tags:
  - annotations:
      description: DEPRECATED and not updated, use wildfly-s2i. Build and run WildFly applications on UBI 8 and JDK 17. For more
        information about using this builder image, including OpenShift considerations,
        see https://github.com/wildfly/wildfly-s2i/blob/main/README.md.
      iconClass: icon-wildfly
      openshift.io/display-name: WildFly S2I builder, JDK 17 (Latest)
      openshift.io/provider-display-name: Red Hat, Inc.
      supports: jee,java
      tags: builder,wildfly,java
    from:
      kind: DockerImage
      name: quay.io/wildfly/wildfly-s2i-jdk17:latest
    referencePolicy:
      type: Local
    name: latest
